<?php

// Auto-generated by SmartestHelper - Do Not Edit



SmartestHelper::register('Ajax');

class SmartestAjaxHelper extends SmartestHelper{
	
	static function createAutoServerClass(){
		
		$ajaxModules[0]['class'] = "Sets";
		$ajaxModules[1]['class'] = "Settings";

		$autoGenerateClass = "
		class AutoServer extends HTML_AJAX_Server {
		// this flag must be set for your init methods to be used
			var \$initMethods = true;
			";
			
		foreach($ajaxModules as $module){
			$autoGenerateClass .= "
			// init method for my class
				function init".$module['class']."() {
					require_once \"Modules/".$module['class'].".class.php\";
					\$module =& new ".$module['class']."();
					\$this->registerClass(\$module);
				}";
		}
	
		$autoGenerateClass .= "}	
		\$server =& new AutoServer();	
		\$server->handleRequest();
		";
		
	}

}



SmartestHelper::register('Authentication');

class SmartestAuthenticationHelper extends SmartestHelper{

	private $database;
	protected $userId;
	protected $user;
	protected $userLoggedIn;
	
	function __construct(){
		
		$this->database = SmartestPersistentObject::get('db:main');
		
		if(SmartestPersistentObject::get('user:isAuthenticated')){
			$this->userLoggedIn =& SmartestPersistentObject::get('user:isAuthenticated');
		}else{
			$this->userLoggedIn = false;
			SmartestPersistentObject::set('user:isAuthenticated', false);
		}		
	}

	function newLogin($username, $password, $service='smartest'){
		if($user = $this->checkLoginDetails($username, $password, $service)){
			// $this->
			return $user;
		}else{
			return false;
		}
	}
	
	function checkLoginDetails($username, $password, $service){
		
		$sql = "SELECT * FROM Users WHERE username='".mysql_real_escape_string($username)."' AND password='".md5($password)."'";
		$user = $this->database->queryToArray($sql);
		
		if(count($user) > 0){
			
			// SmartestSession::set('user:array', $user[0]);
			
			$userObj = new SmartestUser;
			$userObj->hydrate($user[0]);
			
			$userObj->getTokens();
			
			// print_r($userObj);
			
			// SmartestPersistentObject::set('user', $userObj);
			
			// delete these eventually
			// $_SESSION["user"] = $user[0];
			// $this->user =& $_SESSION["user"];
			// $_SESSION["userLoggedIn"] = "TRUE";
			
			SmartestSession::set('user:isAuthenticated', true);
			
			// 
			$this->userLoggedIn =& SmartestPersistentObject::get('user:isAuthenticated');
			$this->getUserPermissionTokens();
			
			return $userObj;
		}else{
			return false;
		}
	}
	
	function getUserIsLoggedIn(){
		
		if($this->userLoggedIn){
			return true;
		}else{
			return false;
		}
	}
	
	function getUserPermissionTokens(){
		
		$sql = "SELECT UserTokens.token_code FROM UsersTokensLookup,UserTokens WHERE UsersTokensLookup.utlookup_user_id='".$_SESSION["user"]["user_id"]."' AND UsersTokensLookup.utlookup_token_id=UserTokens.token_id";
		
		$result = $this->database->queryToArray($sql);
		
		foreach($result as $key=>$token){
			$tokens[$key]=$token['token_code'];
		}
		
		// $_SESSION["user"]["tokens"] = $tokens;
		
		return $_SESSION["user"]["tokens"];
		
	}
	
	function logout(){
		$this->userLoggedIn = false;
		// SmartestPersistentObject::set('user:isAuthenticated', false);
		SmartestSession::clearAll();
		$this->user = array();
	}

}



SmartestHelper::register('Configuration');

class SmartestConfigurationHelper extends SmartestHelper{

	var $options;

	function __construct(){
	
	}
	
	function getUserOptions(){
		
		// Load general user options
		if(SmartestCache::hasData('main_user_options', true) && !(defined('SM_DEVELOPER_MODE') && constant('SM_DEVELOPER_MODE'))){
			$useroptions = SmartestCache::load('main_user_options', true);
		}else{
			if($useroptions = @parse_ini_file(SM_ROOT_DIR."Configuration/options.ini")){
				if(defined('SM_DEVELOPER_MODE') && constant('SM_DEVELOPER_MODE')){
					SmartestCache::save('main_user_options', $useroptions, -1, true);
				}
			}else{
				throw new SmartestException('Error parsing configuration file: '.SM_ROOT_DIR."Configuration/options.ini");
			}
		}
		
		// define constants
		foreach($useroptions as $varname => $value){
			$constant_name = "SM_OPTIONS_".strtoupper($varname);
			
			if(!defined($constant_name)){
				define($constant_name, $value);
			}
		}
		
		return $useroptions;
	}
	
	function getSystemOptions(){
		
		// Load system options
		if(SmartestCache::hasData('system_options', true) && !(defined('SM_DEVELOPER_MODE') && constant('SM_DEVELOPER_MODE'))){
			$systemoptions = SmartestCache::load('system_options', true);
		}else{
			if($systemoptions = @parse_ini_file(SM_ROOT_DIR."Configuration/system.ini")){
				if(defined('SM_DEVELOPER_MODE') && constant('SM_DEVELOPER_MODE')){
					SmartestCache::save('system_options', $systemoptions, -1, true);
				}
			}else{
				throw new SmartestException('Error parsing configuration file: '.SM_ROOT_DIR."Configuration/system.ini");
			}
		}
		
		// define constants
		foreach($systemoptions as $varname => $value){
			$constant_name = "SM_SYSTEM_".strtoupper($varname);

			if(!defined($constant_name)){
				define($constant_name, $value);
			}
		}
		
		return $systemoptions;
	}
	
	function getMeasuringUnits(){
		$unit_groups = array();
		if(is_file("Configuration/units.ini")){
			$raw_units = @parse_ini_file(SM_ROOT_DIR."Configuration/units.ini", true);
			if(is_array($raw_units)){
				$unit_groups = $raw_units;
			}
		}
	}
	
	function flushAll(){
		
		SmartestCache::clear('main_user_options', true);
		SmartestCache::clear('system_options', true);
		
		/*$_SESSION["useroptions"] = parse_ini_file(SM_ROOT_DIR."Configuration/options.ini");
		$useroptions =& $_SESSION["useroptions"];
		foreach($useroptions as $varname=>$value){
			$constant_name = "SM_OPTIONS_".strtoupper($varname);
			// echo $constant_name;
			if(!defined($constant_name)){
				define($constant_name, $value);
			}
		}
		
		$_SESSION["systemoptions"] = parse_ini_file(SM_ROOT_DIR."Configuration/system.ini");
		$systemoptions =& $_SESSION["systemoptions"];
		foreach($systemoptions as $varname=>$value){
			$constant_name = "SM_SYSTEM_".strtoupper($varname);
			// echo $constant_name;
			if(!defined($constant_name)){
				define($constant_name, $value);
			}
		} */
	}
	
	function getRegistrationCode(){
		if(is_file("System/CoreInfo/registration.ini")){
			$reg_file_contents = parse_ini_file(SM_ROOT_DIR."System/CoreInfo/registration.ini");
			if($reg_file_contents['reg_key']){
				return $reg_file_contents['reg_key'];
			}else{
				return false;
			}
		}else{
			return false;
		}
	}
	
	function setRegistrationCode($code){
		
	}
	
	function getRegistrationCodeIsValid($code){
		
	}
	
	public static function parseConfigDataArray($data, $prefix){
	    
	    $final_array = array();
	    
	    if(is_array($data)){
	        
	        // $final_array[$prefix] = $data;
	        
	        foreach($data as $key => $value){
	            
	            $new_prefix = $prefix.'/'.$key;
	            $new_data = SmartestConfigurationHelper::parseConfigDataArray($value, $new_prefix);
	            
	            if(is_array($new_data)){
	                $final_array[$new_prefix] = $new_data;
	            }else{
	                $final_array[$key] = $new_data;
	            }
	            
	            echo '$new_prefix is '.$new_prefix.' and $key is '.$key.'. ';
	            
	            echo "<br />\n";
	            // $final_array[$key] = SmartestConfigurationHelper::parseConfigDataArray($value, $new_prefix);
	            
	        }
	        
	        if(is_array($final_array[$new_prefix])){
	            foreach($final_array[$new_prefix] as $key => $value){
	                $next_prefix = $new_prefix.'/'.$key;
	                $final_array[$next_prefix] = $new_data[$key];
	            }
            }
	        
	    }else{
	        // return array($prefix=>$data);
	        return $data;
	    }
	    
	    return $final_array;
	}

}



SmartestHelper::register('Download');

/**
 * undocumented class
 *
 * @package Smartest
 * @author Marcus Gilroy-Ware
 **/
class SmartestDownloadHelper extends SmartestHelper{
    
    const SM_DOWNLOAD_LOCAL_FILE = 1;
    const SM_DOWNLOAD_STRING = 2;
    
    protected $_local_file;
    protected $_mime_type = 'application/force-download';
    protected $_ready_to_send = false;
    protected $_download_filename;
    protected $_type = 1;
    protected $_string = null;
    
    public function __construct($local_file_path){
        
        // echo $local_file_path;
        
        if(file_exists(utf8_decode($local_file_path))){
            // the user is downloading a file
            $this->_local_file = $local_file_path;
            $this->_ready_to_send = true;
            $this->_download_filename = basename($this->_local_file);
            $this->_type = self::SM_DOWNLOAD_LOCAL_FILE;
        }else{
            // the user is just sending a string - they will need to provide a file name
            $this->_ready_to_send = false;
            $this->_type = self::SM_DOWNLOAD_STRING;
            $this->_string = $local_file_path;
        }
    }
    
    public function getLocalFile(){
        return $this->_local_file;
    }
    
    public function setMimeType($mime_type){
        if(preg_match('/[\w]+\/[\w-]+/', $mime_type)){
            $this->_mime_type = $mime_type;
        }
    }
    
    public function getMimeType(){
        return $this->_mime_type;
    }
    
    public function setDownloadFilename($filename){
        // we used basename so that anybody who mistakenly hands it a full path doesn't break it :)
        $this->_download_filename = basename($filename);
    }
    
    public function getDownloadFilename(){
        return $this->_download_filename;
    }
    
    public function getType(){
        return $this->_type;
    }
    
    public function getDowloadableContent(){
        if($this->_type == self::SM_DOWNLOAD_LOCAL_FILE){
            return SmartestFileSystemHelper::load($this->_local_file);
        }else if($this->_type == self::SM_DOWNLOAD_STRING){
            return $this->_string;
        }
    }
    
    public function getDownloadSize(){
        if($this->_type == self::SM_DOWNLOAD_LOCAL_FILE){
            // echo utf8_decode($this->_local_file);
            return (string)(filesize(utf8_decode($this->_local_file)));
        }else if($this->_type == self::SM_DOWNLOAD_STRING){
            return mb_strlen($this->_string);
        }
    }
    
    public function send(){
        header("Cache-Control: public, must-revalidate\r\n");
        header("Expires: Mon, 26 Jul 1997 05:00:00 GMT\r\n");
        header('Last-Modified: '.gmdate( 'D, d M Y H:i:s' ). ' GMT'."\r\n");
        header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
        header('Pragma: public');
        header("Content-Type: ".$this->_mime_type."; charset=utf-8\r\n");
        // header('Content-Type: text/html; charset=utf-8');
        header("Content-Length: ".$this->getDownloadSize()."\r\n");
        header('Content-Disposition: attachment; filename='.$this->_download_filename." \r\n");
        // readfile($this->_local_file);
        echo $this->getDowloadableContent();
        exit;
    }

} // END class 



SmartestHelper::register('FileSystem');

class SmartestFileSystemHelper extends SmartestHelper{

	static function getDirectoryContents($directory){
	
		$files = array();
		
		if(is_dir($directory)){
		
			$res = opendir($directory);
			
			while (false !== ($file = readdir($res))) {
        		
        		if($file != '.' && $file != '..'){
        			$files[] = $file;
        		}
        		
			}
			
			closedir($res);
			
			return $files;
		}
	}
	
	static function include_all($directory, $recursive=false, $exclusions=''){
		$items = self::getDirectoryContents($directory);
	}
	
	static function include_group(){
		
		$files = func_get_args();
		
		if(defined('SM_DEVELOPER_MODE') && constant('SM_DEVELOPER_MODE')){
			
			foreach($files as $file){
				
				if(file_exists(SM_ROOT_DIR.$file)){
					include SM_ROOT_DIR.$file;
				}
				
			}
			
		}else{
		
			// create consistent hash and filename
			$files_in_order = $files;
			sort($files_in_order);
			$hash = md5(implode('_', $files_in_order));
			$filename = $hash.'.php';
		
			if(!file_exists(SM_ROOT_DIR.'System'.DIRECTORY_SEPARATOR.'Cache'.DIRECTORY_SEPARATOR.'Includes'.DIRECTORY_SEPARATOR.utf8_decode($filename))){
		
				$singlefile = '';
		
				// create single include file
				foreach($files as $file){
					if(file_exists(utf8_decode($file))){
						$singlefile .= file_get_contents(utf8_decode($file));
					}else{
						// ERROR
						return false;
					}
				}
			
				$filenames = "\n\n/**\n  * This file is a cached combination of the following files, included as one files to improve speed:\n\n  * ".implode("\n  * ", $files)."\n\n  */";
		
				$singlefile = str_replace('<'.'?php', "\n\n", $singlefile);
				$singlefile = str_replace('?'.'>', "\n\n", $singlefile);
				$singlefile = "<"."?php\n\n// Auto-generated by SmartestFileSystemHelper - Do Not Edit".$filenames.$singlefile;
		
				file_put_contents(SM_ROOT_DIR.'System'.DIRECTORY_SEPARATOR.'Cache'.DIRECTORY_SEPARATOR.'Includes'.DIRECTORY_SEPARATOR.$filename, $singlefile);
		
			}
		
			include(SM_ROOT_DIR.'System'.DIRECTORY_SEPARATOR.'Cache'.DIRECTORY_SEPARATOR.'Includes'.DIRECTORY_SEPARATOR.$filename);
		
		}
		
	}
	
	static function getFileName($path){
		
	}
	
	static function getDirectoryName($file){
		
	}
	
	static function isSafeFileName($file_path, $intended_dir=''){
	    
	    if(!strlen($intended_dir)){
	        $intended_dir = constant('SM_ROOT_DIR');
	    }
	    
	    $attempted_dir_path = dirname(realpath($file_path)); // for example, /etc/ for ../../../../../../../etc/passwd
	    $intended_dir_path = dirname(realpath($intended_dir));
	    
	    if(mb_strlen($intended_dir_path) >= mb_strlen($attempted_dir_path)){
	        
	        // /var/vsc/smartest/trunk/Presentation/ is longer that /etc/, so compare first five chars of both
	        
	        if(mb_substr($intended_dir_path, 0, mb_strlen($attempted_dir_path)) == $attempted_dir_path){
	            return true;
	        }else{
	            return false;
	        }
	    }else{
	        
	        // otherwise do the exact same thing but the other way around
	        
	        if(mb_substr($attempted_dir_path, 0, mb_strlen($intended_dir_path)) == $intended_dir_path){
	            return true;
	        }else{
	            return false;
	        }
	    }
	    
	}
	
	static function load($path, $binary_safe=false){
	    
	    if(is_dir(utf8_decode($path))){
	        return self::getDirectoryContents($path);
	    }else if(is_file(utf8_decode($path))){
	        
	        if($binary_safe){
	            $mode = 'rb';
	        }else{
	            $mode = 'r';
	        }
	        
            if($handle = fopen(utf8_decode($path), $mode)){
                
                // echo $path.' ';
                // var_dump(is_file($path));
                
                $size = filesize(utf8_decode($path)) ? filesize(utf8_decode($path)) : 1;
                
                $content = fread($handle, $size);
                fclose($handle);
                return $content;
                
            }else{
                // return "file could not be read";
                return false;
            }
	    }
	}
	
	static function move($old_path, $new_path){
	    if(@copy(utf8_decode($old_path), $new_path)){
	        @unlink($old_path);
	        return true;
	    }else{
	        return false;
	    }
	}
	
	static function save($path, $data, $binary_safe=false){
	    
	    if($binary_safe){
            $mode = 'wb';
        }else{
            $mode = 'w';
        }
        
        $handle = fopen(utf8_decode($path), $mode);
        
        if($handle){
            
            $result = fwrite($handle, $data);
            fclose($handle);
            return $result;
            
        }else{
            return false;
        }
	}
	
	static function getUniqueFileName($full_path){
	    
	    if(!strlen($full_path)){
	        $full_path = SM_ROOT_DIR.'Public'.DIRECTORY_SEPARATOR.'Resources'.DIRECTORY_SEPARATOR.'Assets'.DIRECTORY_SEPARATOR.'Untitled_File.tmp';
	    }
	    
	    if(!SmartestStringHelper::startsWith($full_path, '/') && !SmartestStringHelper::startsWith($full_path, '\\')){
	        $full_path = SM_ROOT_DIR.$full_path;
	    }
	    
	    if(!file_exists(utf8_decode($full_path))){
	        
	        // THE FILE DOESN'T ALREADY EXIST, SO JUST GIVE THE NAME BACK
	        return $full_path;
	        
	    }else{
	        
	        // THE FILE ALREADY EXISTS! MAKE A NEW ONE
	        
	        // break up the directories
    	    $path_parts = preg_split('/(\/|\\\)/', $full_path);

    	    // the fastest way of getting the filename without the directory
    	    $actual_file = end($path_parts);
    	    
    	    // the reason we do it like this is because dirname() and basename() throw errors if the files don't exist - this way we can control that.
    	    $negative_start = (mb_strlen($actual_file) * -1);
    	    $directory = mb_substr($full_path, 0, $negative_start);
    	    
    	    $file_without_suffix = SmartestStringHelper::removeDotSuffix($actual_file);
    	    $file_suffix = SmartestStringHelper::getDotSuffix($actual_file);
    	    
    	    if(preg_match('/(.+)-(\d+)$/', $file_without_suffix, $matches)){
    	        $number = $matches[2];
    	        $file_name_trunk = $matches[1];
    	        $try_file = $actual_file;
    	    }else{
    	        $try_file = $file_without_suffix.'-1.'.$file_suffix;
    	        $file_name_trunk = $file_without_suffix;
    	        // return $directory.$new_file_name;
    	    }
	        
	        if(is_dir($directory)){
                
                $contents = self::getDirectoryContents($directory);
                
                $max_tries = 10000;
                $counter = 1;
                
                while($counter < $max_tries && in_array($try_file, $contents)){
                    $counter++;
                    $try_file = $file_name_trunk.'-'.$counter.'.'.$file_suffix;
                }
                
                return $directory.$try_file;
                
            }else{
                return null;
            }
        
        }
	    
	}
	
	static function getFileSuffix($file){
		return SmartestStringHelper::getDotSuffix($file);
	}
	
	static function setSuffix(){
		
	}

}



SmartestHelper::register('HttpRequest');

class SmartestHttpRequestHelper extends SmartestHelper{
	
	static function getContent($address, $correctResources=true, $type='GET', $variables=''){
		
		if(substr($address, 0, 7) != 'http://' && substr($address, 0, 8) != 'https://'){
			$address = 'http://'.$address;
		}
		
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $address);
		curl_setopt($ch, CURLOPT_HEADER, 0);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_USERAGENT, 'Smartest Bot (Version'.SM_SYSTEM_VERSION.')');
		
		if($type == 'POST'){
			curl_setopt($ch, CURLOPT_POST, 1);
		}
		
		$page = curl_exec($ch);
		curl_close($ch);
		
		
		if($correctResources){
		
			$res = self::getExternalResources($page);
			$protocol = (self::isSecure($address)) ? 'https://' : 'http://';
			$protocol_length = strlen($protocol);
			$hostname = self::getHostName($address);
		
			if(is_array($res)){
				foreach($res as $resource_url){
					if($resource_url{0} == '/'){
						// echo 'replaced '.$resource_url. ' with '.$protocol.$hostname.$resource_url.'<br />';
						$page = str_replace($resource_url, $protocol.$hostname.$resource_url, $page);
					}else{
						// echo substr($resource_url, 0, $protocol_length).' '.$protocol.'<br />';
						// echo $resource_url;
						if(substr($resource_url, 0, $protocol_length) != $protocol){
							// echo 'replaced '.$resource_url. ' with '.$protocol.$hostname.'/'.$resource_url.'<br />';
							$page = str_replace($resource_url, $protocol.$hostname.'/'.$resource_url, $page);
						}
					}
				}
			}
		
		}
		
		return $page;
		
	}
	
	static function getHostName($address){
		
		preg_match('/^https?:\/\/([\w\.]{7,})\//', $address, $matches);
		return $matches[1];
	}
	
	static function getHostAddress($address){
		
		// $host = self::getHostName($address);
		// return `host $host`;
	}
	
	static function getExternalResources($page){
		
		if(substr($page, 0, 7) == 'http://' || substr($page, 0, 8) == 'https://'){
			$html = self::getContent($page, false);
		}else{
			$html = $page;
		}
		
		preg_match_all('/<(link|script|img)[^>]+(href|src)=[\'"](\.{0,2}\/?[^\'"]+)/', $html, $matches);
		preg_match_all('/<style[^>]+>@import ((url\()?[\'"]?([\w\.\/]+)[\'"]?\)?);/', $html, $matches_2);
		
		$res = $matches[3];
		$css_imports = $matches_2[3];
		
		foreach($css_imports as $css){
			if(!in_array($css, $res)){
				$res[] = $css;
			}
		}
		
		return $res;
	}
	
	static function getTitle($page){
		
		if(substr($page, 0, 7) == 'http://' || substr($page, 0, 8) == 'https://'){
			$html = self::getContent($page, false);
		}else{
			$html = $page;
		}
		
		preg_match('/<title>(.+)<\/title>/', $html, $matches);
		
		return $matches[1];
		
	}
	
	static function getMetas($page){
		
		if(substr($page, 0, 7) == 'http://' || substr($page, 0, 8) == 'https://'){
			$html = self::getContent($page, false);
		}else{
			$html = $page;
		}
		
		preg_match_all('/<meta (name|http-equiv)=[\'"]?([^"\']+)[\'"]? content=[\'"]?([^"\']*)[\'"]?/', $html, $matches);
		
		$metas = array();
		
		foreach($matches[0] as $key=>$meta){
			$metas[$key]['name'] = $matches[2][$key];
			$metas[$key]['value'] = $matches[3][$key];
			$metas[$key]['type'] = ($matches[1][$key] == 'http-equiv') ? 'http-equiv' : 'normal';
		}
		
		return $metas;
		
	}
	
	static function isSecure($address){
		return (substr($address, 0, 8) == 'https://');
	}
	
}







SmartestHelper::register('Json');

class SmartestJsonHelper extends SmartestHelper{
	
}



// a class for checking if libraries are installed

SmartestHelper::register('Lib');

class SmartestLibHelper extends SmartestHelper{

	static function isInstalled($library){
		
		if(SmartestCache::hasData('libraries_data', true)){
			$libs = SmartestCache::load('libraries_data', true);
		}else{
			$rawlibs = SmartestXmlHelper::loadFile('System/CoreInfo/libraries.xml');
			$libraries = array();
			foreach($rawlibs['library'] as $lib){
				if(!array_key_exists($lib['name'], $libraries)){
					$libraries[$lib['name']] = $lib;
				}
			}
			SmartestCache::save('libraries_data', $libraries, -1, true);
		}
		
		$name_parts = explode("/", $library);
		
		switch(count($name_parts)){
			case '2':
				// $file = SmartestStringHelper::toCamelCase();
				break;
			case '1':
				// $file = SmartestStringHelper::toCamelCase();
				break;
		}
		
	}
	
	static function load($library){
		
	}
	
	static function getLoaded(){
		if(SmartestCache::hasData('libraries_data', true)){
			$libs = SmartestCache::load('libraries_data', true);
		}else{
			$libs = SmartestXmlHelper::loadFile('System/CoreInfo/libraries.xml');
		}
		
		return $libs;
	}
	
	static function isLoaded($library){
		
	}

}



SmartestHelper::register('String');

class SmartestStringHelper extends SmartestHelper{

	static function random($size){
	
		$possValues = array("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s"
			    , "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", 
			    "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9");
		$stem = "";
	
		for($i=0; $i<$size; $i++){
			$randNum = rand(0, count($possValues)-1);
			$shoot = $possValues[$randNum];
			$plant = $stem.$shoot;
			$stem = $plant;
		}	
	
		return $plant;
	
	}

	static function toSlug($normal_string){
	
		$page_name = strtolower($normal_string);
		$page_name = trim($page_name, " ?!%$#&£*|()/\\");
		$page_name = preg_replace("/[\"'\.,\(\)]+/", "", $page_name);
		$page_name = preg_replace("/[^\w-]+/", "-", $page_name);
		return $page_name;
	
	}
	
	static function toVarName($normal_string){
	
		$page_name = strtolower($normal_string);
		$page_name = trim($page_name, " ?!%$#&£*|()/\\");
		$page_name = preg_replace("/[\"'\.,\(\)]+/", "", $page_name);
		$page_name = preg_replace("/[^\w_-]+/", "_", $page_name);
		return $page_name;
	
	}
	
	static function toConstantName($string){
		
		$constant_name = trim($string, " ?!%$#&£*|/\\");
		$constant_name = preg_replace("/[\"'\.,]+/", "", $constant_name);
		$constant_name = preg_replace("/[^\w-_]+/", "_", $constant_name);
		$constant_name = strtoupper($constant_name);
    	
    	return $constant_name;
	}
	
	static function toCamelCase($string, $omitfirst=false){
		// takes a string, splits it by -, _, or '', and returns it lowercase with the first letter of each 'word' being uppercase
		$string = self::toSlug($string);
		$words = preg_split('/[_-]/', $string);
		$final = '';
		
		$i = 0;
		
		foreach($words as $word){
			$word = strtolower($word);
			
			if($omitfirst == true && $i == 0){
			    
		    }else{
		        $word = self::capitalizeFirstLetter($word);
		    }
			
			$final .= $word;
			$i++;
		}
		
		return $final;
		
	}
	
	static function toQueryString($array, $escapeAmpersand=false){
	    if(is_array($array)){
	        
	        $i = 0;
	        $string = '';
	        $amp = $escapeAmpersand ? '&amp;' : '&';
	        
	        foreach($array as $key => $value){
	            
	            if($i > 0){
	                $string .= $amp;
	            }
	            
	            $string .= $key .'='.$value;
	            
	            $i++;
	        }
	        
	        return $string;
	    }
	}
	
	static function capitalizeFirstLetter($string){
	    $string{0} = strtoupper($string{0});
	    return $string;
	}
	
	static function toTitleCase($string){
	    
        $non_capitalised_words = array('to', 'the', 'and', 'in', 'of', 'with', 'a', 'an');
        $words = explode(' ', $string);
        $new_string = '';
        
        foreach($words as $key=>$word){
            if($key = 0){
                $new_string = $word;
            }else{
                if(in_array($word, $non_capitalised_words)){
                    $new_string .= ' '.$word;
                }else{
                    $new_string .= ' '.self::capitalizeFirstLetter($word);
                }
            }
        }
        
        return $new_string;
	}
	
	static function isMd5Hash($string){
		if(preg_match("/^[0-9a-f]{32}$/", $string)){ // if
			return true;
		}else{
			return false;
		}
	}
	
	static function endsWith($word, $symbol){
	    if(mb_strlen($word)){
	        $pos = (mb_strlen($word) - 1);
	        if($word{$pos} == $symbol){
	            return true;
	        }else{
	            return false;
	        }
	    }else{
	        return false;
	    }
	}
	
	static function startsWith($word, $symbol){
	    if(mb_strlen($word)){
	        $pos = 0;
	        if($word{$pos} == $symbol){
	            return true;
	        }else{
	            return false;
	        }
	    }else{
	        return false;
	    }
	}
	
	static function getDotSuffix($filename){
	    
	    $file = end(explode('/', $filename));
	    
	    if(strpos($file, '.') === false){
	        return null;
	    }else{
	        return end(explode('.', $file));
	    }
	}
	
	static function removeDotSuffix($filename){
	    
	    $dot_pieces = explode('.', $filename);
	    
	    if(count($dot_pieces) < 2){
	        return null;
        }else{
            $suffix = end($dot_pieces);
            $ns = ((mb_strlen($suffix)+1) * -1);
            $result = mb_substr($filename, 0, $ns);
            return $result;
        }
	}
	
	static function sanitizeFileContents($string){
	    
	    $string = str_replace('

', '', $string);
	    $string = str_replace('DELETE FROM', '', $string);
	    $string = str_replace('DROP TABLE', '', $string);
	    $string = str_replace('DROP DATABASE', '', $string);
	    
	    return $string;
	    
	}
	
	static function toSensibleFileName($string){
	    $suffix = self::getDotSuffix($string);
	    $base = self::removeDotSuffix($string);
	    $base = preg_replace("/[\s\.]/", '_', $base);
	    return $base.'.'.$suffix;
	}
	
	static function toSummary($string, $char_length=300){
	    // find the end of first paragraph and cut there
	    preg_match_all('/<p[^>]*>(.+?)<\/p>/', $string, $paragraphs);

	    if(count($paragraphs[0])){
	        $first_paragraph = $paragraphs[1][0];
	    }else{
	        $first_paragraph = $string;
	    }
	    
	    // strip tags
	    $final_string = strip_tags($first_paragraph);
	    
	    // if it is longer that $char_length, truncate it and add '...'
	    if(strlen($final_string) > $char_length){
	        $final_string = substr($final_string, 0, ($char_length - 3)).'...';
	    }
	    
	    return $final_string;
	    
	}
	
	static function isEmailAddress($string){
		
	}
	
	static function getRelatedWords($word){
		// query wikipedia
		
	}
	
	static function toHtmlEntities($string){
    	return htmlentities($string, ENT_QUOTES, 'UTF-8') ;
    }

}



SmartestHelper::register('Upload');

class SmartestUploadHelper extends SmartestHelper{
    
    protected $_upload_name = null;
    protected $_directory = null;
    protected $_file_name = null;
    protected $_temp_file_name = null;
    protected $_original_file_name = null;
    
	function __construct($upload_name, $new_file_dir='', $new_file_name=''){
		
		if(isset($_FILES[$upload_name]) && $_FILES[$upload_name]){
		    
		    $this->_upload_name = $upload_name;
		    
		    if(!@strlen($new_file_name)){
    			$this->_file_name = $_FILES[$this->_upload_name]['name'];
    		}
    		
    		$this->_original_file_name = $_FILES[$this->_upload_name]['name'];
    		$this->_temp_file_name = $_FILES[$this->_upload_name]['tmp_name'];
    		
    		if(strlen($new_file_dir)){
    		    $this->setUploadDirectory($new_file_dir);
		    }
		
	    }else{
	        // ERROR - upload doesn't exist
	        // echo 'Error $_FILES['.$upload_name.'] doesn\'t exist.';
	    }
		
	}
	
	function save(){
	    if(@move_uploaded_file($_FILES[$this->_upload_name]['tmp_name'], $this->getUploadDirectory().$this->getFileName())){
	        return true;
        }else{
            return false;
        }
	}
	
	function hasDotSuffix(){
	    
	    if($this->getFileName()){
	        
	        $args = func_get_args();
	        
	        if(count($args)){
	            
	            if(is_array($args[0])){
	                $suffixes = $args[0];
	            }else{
	                $suffixes = $args;
	            }
	        
	            foreach($suffixes as $s){
	                if(SmartestStringHelper::getDotSuffix($this->getFileName()) == $s){
	                    return true;
	                }
	            }
	        
            }
	        
	        return false;
        }
	}
	
	function setFileName($file_name){
	    
	    // $max_tries = 1;
	    
	    if($this->getUploadDirectory()){
	    
	        /*while(file_exists($this->getUploadDirectory().$file_name) && $max_tries < 1000){
	            $file_name = $file_name.'_'.$max_tries;
	        }*/
	        
	        $file_name = basename(SmartestFileSystemHelper::getUniqueFileName($this->getUploadDirectory().$file_name));
	        $this->_file_name = $file_name;
	        
        }
	}
	
	function getFileName(){
	    return $this->_file_name;
	}
	
	function getOriginalFileName(){
	    return $this->_original_file_name;
	}
	
	function setUploadDirectory($directory){
	    
	    if(!SmartestStringHelper::startsWith($directory, '/')){
	        $directory = SM_ROOT_DIR.$directory;
	    }
	    
	    if(is_dir($directory) && is_writable($directory)){
	        
	        if(SmartestStringHelper::endsWith($directory, '/')){
    	        $this->_directory = $directory;
		    }else{
		        $this->_directory = $directory.'/';
		    }
	    }
	    
	    // recalculate file name to make sure it is still unique in the new directory.
	    $this->setFileName($this->_file_name);
	    
	}
	
	function getUploadDirectory(){
	    return $this->_directory;
	}
	
	function getName(){
	    return $this->_upload_name;
	}
	
}



SmartestHelper::register('UserAgent');

class SmartestClientSideUserAgentObject{
	
	public $platform;
	public $appName;
	public $appVersion;
	public $engine;
	public $isGecko;
	public $language;
	
}

class SmartestUserAgentHelper extends SmartestHelper{
	
	protected $browser = array();
	protected $simpleObject;
	protected $userAgent;
	
	function __construct(){
    	
    	$this->userAgent = $_SERVER['HTTP_USER_AGENT'];
    	
    	//language
		if($languages = getenv('HTTP_ACCEPT_LANGUAGE')){
			$languages = preg_replace('/(;q=[0-9]+.[0-9]+)/i','',$languages);
    	}else{
			$languages = 'en-us';
    	}
    	
        $this->browser['language'] = $languages; 
	}
	
	public function getPlatform(){
	    
	    if(!isset($this->browser['platform'])){
	    
	        // detect platform	    
    	    if(preg_match('/Win(dows|98|95|32|16|NT|XP)/i', $this->userAgent)) {
    	  	    $this->browser['platform'] = 'Windows';
   		    }else if(stripos($this->userAgent, 'Mac')) {
    	  	    $this->browser['platform'] = 'Macintosh';
    	    }else if(stripos($this->userAgent, 'linux')) {
    	  	    $this->browser['platform'] = 'GNU/Linux';
            }else if(stripos($this->userAgent, 'unix')) {
                $this->browser['platform'] = 'Unix';
    	    }else{
    	 	    $this->browser['platform'] = 'Unknown';
    	    }
    	}
    	
    	return $this->browser['platform'];
    	
	}
    
    public function getAppName(){
	    
	    if(!isset($this->browser['appName'])){
	    
	        // detect browser program
		    if (stripos($this->userAgent, 'MSIE')){
                $this->browser['appName'] = 'Explorer';
    	    }else if (stripos($this->userAgent, 'Safari')) {
                $this->browser['appName'] = 'Safari';
    	    }else if (stripos($this->userAgent, 'Firefox')) {
                $this->browser['appName'] = 'Firefox';
    	    }else if (stripos($this->userAgent, 'Opera')) {
                $this->browser['appName'] = 'Opera';
            }else if (stripos($this->userAgent, 'OmniWeb')) {
                $this->browser['appName'] = 'OmniWeb';
            }else if (stripos($this->userAgent, 'Netscape')) {
                $this->browser['appName'] = 'Netscape';
            }else if (stripos($this->userAgent, 'Camino')) {
                $this->browser['appName'] = 'Camino';
            }else{
    		    $this->browser['appName'] = 'Unknown';
    	    }
    	}
    	
	    return $this->browser['appName'];
	}
	
	public function getAppVersion(){
	    
	    if(!isset($this->browser['appVersion'])){
	        
    	    if($this->isExplorer()){
    	        // look for number after 'MSIE'
    	        preg_match('/MSIE\s?(\d+\.\d+)/i', $this->userAgent, $matches);
    	        $this->browser['appVersion'] = $matches[1];
    	    }else if($this->isSafari()){
    	        preg_match('/Safari\/((\d+)(\.[\d]+)+)/i', $this->userAgent, $matches);
    	        $build = $matches[2];
    	        switch($build){
    	            case 85:
    	            $this->browser['appVersion'] = '1.0';
    	            break;
    	            case 100:
    	            $this->browser['appVersion'] = '1.1';
    	            break;
    	            case 125:
    	            $this->browser['appVersion'] = '1.2';
    	            break;
    	            case 312:
    	            $this->browser['appVersion'] = '1.3';
    	            break;
    	            case 412:
    	            $this->browser['appVersion'] = '2.0';
    	            break;
    	            case 416:
    	            $this->browser['appVersion'] = '2.0.2';
    	            break;
    	            case 417:
    	            $this->browser['appVersion'] = '2.0.3';
    	            break;
    	            case 419:
    	            $this->browser['appVersion'] = '2.0.4';
    	            break;
    	            case 522:
    	            $this->browser['appVersion'] = '3.0';
    	            break;
    	        }
    	    }else if($this->isFirefox()){
    	        preg_match('/Firefox\/(\d[\d\.]+\d+)/i', $this->userAgent, $matches);
    	        $this->browser['appVersion'] = $matches[1];
    	    }else if($this->isCamino()){
        	    preg_match('/Camino\/(\d[\d\.]+\d+)/i', $this->userAgent, $matches);
        	    $this->browser['appVersion'] = $matches[1];
        	    // echo $this->userAgent;
        	}
    	}
	    
	    return $this->browser['appVersion'];
	}
	
	public function getRenderingEngineName(){
	    
	    if(!isset($this->browser['engine'])){
	    
	        // set engine
            if (stripos($this->userAgent, 'Gecko')) { // rendering engines
                
                if (stripos($this->userAgent, 'KHTML') === FALSE) {
                    $this->browser['engine'] = 'Gecko';
                }else{
                    if(stripos($this->userAgent, 'AppleWebKit') === FALSE){
                        $this->browser['engine'] = 'KHTML';
                    }else{
                        $this->browser['engine'] = 'AppleWebKit';
                    }
                }
                
            }else{
                if($this->isExplorer()){
                    if($this->isMacintosh()){
                        $this->browser['engine'] = 'MSIE for MAC';
                    }else{
                        $this->browser['engine'] = 'MSIE';
                    }
                }
            }
        }
        
        return $this->browser['engine'];
        
	}
    
	// platforms
	public function isMacintosh(){
		return $this->getPlatform() == "Macintosh" ? true : false;
	}
	
	public function isWindows(){
		return $this->getPlatform() == "Windows" ? true : false;
	}
	
	public function isLinux(){
		return $this->getPlatform() == "GNU/Linux" ? true : false;
	}
	
	public function isUnix(){
		return ($this->getPlatform() == "Unix" /* || ($this->isMacintosh() && $this->) */) ? true : false;
	}
	
	// rendering engines
	function isGecko(){
		return $this->getRenderingEngineName() == "Gecko" ? true : false;
	}
	
	// browsers 
	public function isSafari(){
		return $this->getAppName() == "Safari" ? true : false;
	}
	
	public function isExplorer(){
		return $this->getAppName() == "Explorer" ? true : false;
	}
	
	public function isFirefox(){
		return $this->getAppName() == "Firefox" ? true : false;
	}
	
	public function isCamino(){
		return $this->getAppName() == "Camino" ? true : false;
	}
	
	public function getLanguage(){
		return $this->browser['language'];
	}
	
	public function getSimpleClientSideObject(){
	    if(is_object($this->simpleObject)){
	        return $this->simpleObject;
	    }else{
	        $this->simpleObject = new SmartestClientSideUserAgentObject;
	        $this->simpleObject->appName = $this->getAppName();
	        $this->simpleObject->appVersion = $this->getAppVersion();
	        $this->simpleObject->platform = $this->getPlatform();
	        $this->simpleObject->engine = $this->getRenderingEngineName();
	        $this->simpleObject->isGecko = $this->isGecko();
	        $this->simpleObject->language = $this->browser['language'];
	        return $this->simpleObject;
	    }
	}
	
	public function getSimpleClientSideObjectAsJson(){
	    return json_encode($this->getSimpleClientSideObject());
	}

}

// Safari: Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en) AppleWebKit/418.8 (KHTML, like Gecko) Safari/419.3
// full list of user agents at: http://www.pgts.com.au/pgtsj/pgtsj0208c.html



SmartestHelper::register('UserToken');

class SmartestUserTokenHelper extends SmartestHelper{
    
    var $database;
    
    function __construct(){
		$this->database = SmartestPersistentObject::get('db:main');
    }
    
    function getUserHasToken($token, $db=false){
    	if($db==true){
			
			$sql = "SELECT * FROM UsersTokensLookup,UserTokens WHERE UsersTokensLookup.utlookup_user_id='".$_SESSION["user"]["user_id"]."' AND UsersTokensLookup.utlookup_token_id=UserTokens.token_id AND UserTokens.token_code=$token";
			$count = $this->database->howMany($sql);
		
			if($count>0){
				$has_token = 0;
			}else{
				$has_token = 1;
			}
			
		}else{
			$has_token=in_array($token,$_SESSION["user"]["tokens"]);
		}
		
		return $has_token;
    }

    function getUserTokens($db=false){  
    		
    		if($db==true){
			
			$sql = "SELECT UserTokens.token_code FROM UsersTokensLookup,UserTokens WHERE UsersTokensLookup.utlookup_user_id='".$_SESSION["user"]["user_id"]."' AND UsersTokensLookup.utlookup_token_id=UserTokens.token_id";
			$result = $this->database->queryToArray($sql);
			
			foreach($result as $key=>$token){
				$tokens[$key]=$token['token_code'];
			}
			
		}else{
			$tokens = $_SESSION["user"]["tokens"];
		}
		
		return $tokens;
    }
}








/**
 * undocumented class
 *
 * @package Smartest
 * @subpackage XmlHelper
 * @author Marcus Gilroy-Ware
 **/

SmartestHelper::register('Xml');

class SmartestXmlHelper extends SmartestHelper{
	
	static function loadFile($filename){
		
		if(is_file($filename)){
			
			if(!class_exists("XML_Unserializer")){
				@include_once 'PEAR.php';
				@include_once 'XML/Unserializer.php'; 
				@include_once 'XML/Serializer.php';
			}
			
			if(class_exists("XML_Unserializer")){

	    		$option = array('complexType' => 'array', 'parseAttributes' => TRUE);
	    		$unserialized = new XML_Unserializer($option);
	    		$result = $unserialized->unserialize($filename, true);

	    		if (PEAR::isError($result)) {
					// ERROR: XML file could not be parsed: PEAR said "$result->getMessage()"
					// echo 'xml file unparsable';
					return false;
	    		}else{
	    			// load contents from xml file
	    			$data = $unserialized->getUnserializedData();
	    			return $data;
	    		}
	
	    	}else{
	    		// ERROR: XML file could not be parsed because the PEAR XML_Unserializer library could not be found.
				// echo 'required pear libraries missing';
	    	}
		}else{
			// ERROR: File does not exist
			// echo 'no such file';
		}
	}
	
	static function loadString($string){
		
		if(strlen($string)){
			
			if(!class_exists("XML_Unserializer")){
				@include_once 'PEAR.php';
				@include_once 'XML/Unserializer.php'; 
				@include_once 'XML/Serializer.php';
			}
			
			if(class_exists("XML_Unserializer")){

	    		$option = array('complexType' => 'array', 'parseAttributes' => TRUE);
	    		$unserialized = new XML_Unserializer($option);
	    		$result = $unserialized->unserialize($string);

	    		if (PEAR::isError($result)) {
					// ERROR: XML file could not be parsed: PEAR said "$result->getMessage()"
					// echo 'xml file unparsable';
					return false;
	    		}else{
	    			// load contents from xml file
	    			$data = $unserialized->getUnserializedData();
	    			return $data;
	    		}
	
	    	}else{
	    		// ERROR: XML file could not be parsed because the PEAR XML_Unserializer library could not be found.
				// echo 'required pear libraries missing';
	    	}
		}else{
			// ERROR: File does not exist
			// echo 'no such file';
		}
	}
	
} // END class



SmartestHelper::register('Yaml');

// wrapper class for Spyc

include 'Spyc/spyc.php5';

class SmartestYamlHelper extends SmartestHelper{
    
    public static function load($file_name){
        if(is_file($file_name)){
            $array = Spyc::YAMLLoad($file_name);
            return $array;
        }else{
            // error 
        }
    }
    
    public static function create($data_array){
        
    }
    
}



SmartestHelper::register('Download');

class SmartestCmsLinkHelper extends SmartestHelper{
    
    protected $_item;
    protected $_page;
    protected $_host_page;
    protected $_params = array();
    protected $_type;
    protected $_error_message;
    protected $_error = false;
    protected $_draft_mode = false;
    protected $_preview_mode = false;
    protected $_image_file = null;
    protected $_tag_name = null;
    protected $_external_destination = null;
    
    public function __construct($page='', $params='', $draft=false, $preview=false){
        $this->_params = $params;
        
        if(is_object($page)){
            $this->_host_page = $page;
        }
        
        $this->_draft_mode = $draft;
        $this->_preview_mode = $preview;
    }
    
    public function parse($link){
        
        $link_parts = explode(':', $link);
        $type = $link_parts[0];
        
        switch($type){
            
            case "page":
            $this->_type = 'page';
            // print_r($link_parts);
            if($link_parts[1]){
                
                $page_identifier = $link_parts[1];
                
                // echo $page_identifier;
                
                if($lookup = $this->parseLinkIdentifier($page_identifier)){
                    
                    $this->_page = new SmartestPage;
                    
                    if($this->_page->hydrateBy($lookup['key'], $lookup['value'])){
                        // success!
                    }else{
                        $this->_error_message = 'Page not found';
                        $this->_error = true;
                        return false;
                    }
                    
                }else{
                    $this->_error_message = 'Link format invalid';
                    $this->_error = true;
                    return false;
                }
                
            }else{
                // whatever was passed in the to attribute must have ended in a colon, because $link_parts[1] is empty
                $this->_error_message = 'Link format invalid';
                $this->_error = true;
                return false;
            }
            
            break;
            
            case "metapage":
            $this->_type = 'metapage';
            
            if($link_parts[1] && $link_parts[2]){
                
                $page_identifier = $link_parts[1];
                $item_identifier = $link_parts[2];
                
                if($page_lookup = $this->parseLinkIdentifier($page_identifier)){
                    
                    $this->_page = new SmartestPage;
                    // print_r($this->_page);
                    if($this->_page->hydrateBy($page_lookup['key'], $page_lookup['value'])){
                        
                        if($item_lookup = $this->parseLinkIdentifier($item_identifier)){

                            $this->_item = new SmartestItem;
                            
                            if($item_lookup['key'] == 'name'){
                                $key = 'slug';
                            }else{
                                $key = $item_lookup['key'];
                            }
                            
                            if($this->_item->hydrateBy($key, $item_lookup['value'])){
                                // success!
                            }else{
                                $this->_error_message = 'Item not found';
                                $this->_error = true;
                                return false;
                            }

                        }else{
                            $this->_error_message = 'Link format invalid';
                            $this->_error = true;
                            return false;
                        }
                        
                    }else{
                        $this->_error_message = 'Page not found';
                        $this->_error = true;
                        return false;
                    }
                    
                }else{
                    $this->_error_message = 'Link format invalid';
                    $this->_error = true;
                    return false;
                }
                
            }else{
                $this->_error_message = 'Link format invalid';
                $this->_error = true;
                return false;
            }
            
            break;
            
            case "image":
            $this->_type = 'image';
            
            if($link_parts[1]){
                // $image_file = $link_parts[1];
                if(in_array($link_parts[1], array('http', 'https'))){
                    $this->_image_file = $link_parts[1].':'.$link_parts[2];
                }else{
                    $this->_image_file = $link_parts[1];
                }
            }
            
            break;
            
            case "tag":
            $this->_type = 'tag_page';
            
            if($link_parts[1]){
                $this->_tag_name = $link_parts[1];
            }else{
                $this->_error_message = 'A tag name must be provided. Link format invalid.';
                $this->_error = true;
                return false;
            }
            
            break;
            
            default:
            // return
            $this->_type = 'external';
            $this->_external_destination = $link;
            break;
            
        }
        
        return true;
        
    }
    
    public function parseContent($with){
        if(substr($with, 0, 6) == 'image:'){
            return '<img src="'.substr($with, 6).'" alt="'.$this->getContent(true).'" />';
        }else{
            return $with;
        }
    }
    
    public function getContent($ignore_with=false){
        
        if($this->_params['with'] && !$ignore_with){
            return $this->parseContent($this->_params['with']);
        }else{
            
            switch($this->_type){

                case "page":
                return $this->_page->getTitle();
                break;

                case "metapage":
                return $this->_item->getName();
                break;

                case "image":
                return $this->_image_file;
                break;
                
                case "tag_page":
                return $this->_tag_name;
                break;

                case "external":
                return $this->_external_destination;
                break;
            }
            
        }
        
    }
    
    public function getUrl(){
        
        switch($this->_type){
            
            case "page":
            
            if($this->_preview_mode){
                return SM_CONTROLLER_DOMAIN.'websitemanager/preview?page_id='.$this->_page->getWebid();
            }else if($this->shouldUseId()){
                return SM_CONTROLLER_DOMAIN.'website/renderPageFromId?page_id='.$this->_page->getWebid();
            }else{
                return SM_CONTROLLER_DOMAIN.$this->_page->getDefaultUrl();
            }
            
            break;
            
            case "metapage":
            
            // print_r($this->_page);
            
            if($this->_preview_mode){
                return SM_CONTROLLER_DOMAIN.'websitemanager/preview?page_id='.$this->_page->getWebid().'&amp;item_id='.$this->_item->getId();
            }else if($this->shouldUseId()){
                return SM_CONTROLLER_DOMAIN.'website/renderPageFromId?page_id='.$this->_page->getWebid().'&amp;item_id='.$this->_item->getWebid();
            }else{
                $template_url = SM_CONTROLLER_DOMAIN.$this->_page->getDefaultUrl();
                $url = str_replace(':id', $this->_item->getId(), $template_url);
                $url = str_replace(':long_id', $this->_item->getWebid(), $url);
                $url = str_replace(':name', $this->_item->getSlug(), $url);
                return $url;
            }
            
            break;
            
            case "image":
            return SM_CONTROLLER_DOMAIN.'Resources/Images/'.$this->_image_file;
            break;
            
            case "tag_page":
            return SM_CONTROLLER_DOMAIN.'tags/'.$this->_tag_name.'.html';
            break;
            
            case "external":
            return $this->_external_destination;
            break;
        }
        
    }
    
    protected function parseLinkIdentifier($page_identifier){
        
        if(preg_match('/((name|id|webid)=)?([\w-]+)/i', $page_identifier, $matches)){
            
            // print_r($matches);
            if(strlen($matches[2]) && in_array($matches[2], array('name', 'id', 'webid'))){
                $index_key = $matches[2];
            }else{
                $index_key = 'name';
            }
            
            $index_value = $matches[3];
            return array('key'=>$index_key, 'value'=>$index_value);
            
        }else{
            return false;
        }
    }
    
    public function getMarkup(){
        
        if($this->_error){
            if($this->_draft_mode){
                return '<strong>'.$this->_error_message.'</strong>';
            }else{
                return '<!--link failed: '.$this->_error_message.'-->';
            }
        }else{
            
            // put html together
            if($this->shouldOmitAnchorTag()){
                
                $markup = '<!--cold link-->'.$this->getContent();
                
            }else{
                
                $markup = '<a href="'.$this->getUrl().'"';
                
                if($this->_preview_mode){
                    $markup .=' target="_top"';
                }
                
                $markup .='>'.$this->getContent().'</a>';
                
            }
            
        }
        
        return $markup;
        
    }
    
    public function shouldOmitAnchorTag(){
        return $this->isInternalPage() && $this->shouldGoCold() && is_object($this->_host_page) && $this->_page->getId() == $this->_host_page->getId();
    }
    
    public function shouldGoCold(){
        return (isset($this->_params['goCold']) && $this->_params['goCold'] && $this->_params['goCold'] != 'false');
    }
    
    public function shouldUseId(){
        return (isset($this->_params['byId']) && $this->_params['byId'] && $this->_params['byId'] != 'false');
    }
    
    public function isInternalPage(){
        return in_array($this->_type, array('page', 'metapage'));
    }
    
    public function getErrorMessage(){
        return $this->_error_message;
    }
    
}



// include 'XML/Serializer.php';

class SmartestRssOutputHelper{
    
    protected $_limit = 15;
    protected $_items = array();
    protected $_domObject;
    protected $_title;
    protected $_author;
    protected $_data_array = array();
    
    public function __construct($data){
        if(is_array($data)){
            $this->_items = $data;
            if(count($data)){
                
            }
        }else{
            // do nothing
        }
    }
    
    public function getXml(){
        // $xml = new DomDocument;
        
        
        
        // if(class_exists('DOMDocument')){
		//	$this->_domObject = new DOMDocument('1.0');
	    //    $this->_domObject->formatOutput = true;
		//	$this->_domObject->loadXML();
	    // }
	    
	    // $rss = new SimpleXMLElement('<?xml version="1.0" encoding="UTF-8" ?'.'><!-- generator="Smartest 0.6.5" --><rss version="2.0" />');
	    
	    // $channel = new SimpleXMLElement("<channel />");
	    
	    // $rootTagElement = $this->_domObject->getElementsByTagName('rss')->item(0);
	    // $channel = $this->_domObject->createElement("channel");
	    // $rootTagElement->appendChild($channel);
	    // return $this->_domObject->saveXml();
        // $rss = 
        
        $this->_data_array = array();
        
        $options = array(
          XML_SERIALIZER_OPTION_INDENT        => '  ',
          XML_SERIALIZER_OPTION_RETURN_RESULT => true,
          "defaultTagName" => "item"
        );
        
        $serializer = new XML_Serializer($options);
        
        $this->_data_array['channel'] = array(
            'author'=>$this->getAuthor(),
            'title'=>$this->getTitle(),
            'generator'=>'Smartest v 0.6.5'
        );
        
        $this->addItems();
        
        $serializer->setOption("rootName", "rss");
        // $serializer->setOption("scalarAsAttributes", true);
        $serializer->setOption("rootAttributes", array("version" => '0.9'));
        
        if($serializer->serialize($this->_data_array)){
            return $serializer->getSerializedData();
        }
    }
    
    public function send(){
        header("Cache-Control: public, must-revalidate\r\n");
        header("Expires: Mon, 26 Jul 1997 05:00:00 GMT\r\n");
        header('Last-Modified: '.gmdate( 'D, d M Y H:i:s' ). ' GMT'."\r\n");
        header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
        header('Content-Type: text/xml; charset=utf-8');
        echo $this->getXml();
        exit;
    }
    
    public function setLimit($limit){
        if(is_numeric($limit)){
            $this->_limit = ceil($limit);
        }
    }
    
    public function getTitle(){
        return $this->_title;
    }
    
    public function setTitle($t){
        $this->_title = $t;
    }
    
    public function getAuthor(){
        return $this->_author;
    }
    
    public function setAuthor($t){
        $this->_author = $t;
    }
    
    public function addItems(){
        
        $data = array();
        
        foreach($this->_items as $object){
            $item = array();
            $item['title'] = $object->getTitle();
            $item['description'] = $object->getDescription();
            $item['pubDate'] = date('r', $object->getDate());
            $this->_data_array['channel'][] = $item;
        }
        
        return $data;
    }
    
}