<?php

// Auto-generated by Smartest at: 2007-12-04 09:03:42

class autoVideoPodcast extends SmartestCmsItem{

protected $_model_id = 4;

const FLASH_VIDEO_FILE = 13;
const DOWNLOADABLE_VIDEO = 14;
const DESCRIPTION = 15;
const DATE_ADDED = 16;

}