<?php

// Auto-generated by Smartest at: 2007-11-21 04:21:15

class autoArticle extends SmartestCmsItem{

protected $_model_id = 2;

const UPPER_IMAGE = 6;
const PUBLISHED_AT = 7;
const ARTICLE_TEXT = 8;
const LOWER_IMAGE = 9;

}