<?php

define('SM_QUERY_ALL_DRAFT', 0); // 
define('SM_QUERY_ALL_DRAFT_ARCHIVED', 1);
define('SM_QUERY_ALL_DRAFT_CURRENT', 2);

define('SM_QUERY_ALL_LIVE', 3);
define('SM_QUERY_ALL_LIVE_ARCHIVED', 4);
define('SM_QUERY_ALL_LIVE_CURRENT', 5);

define('SM_QUERY_PUBLIC_DRAFT', 6); // 
define('SM_QUERY_PUBLIC_DRAFT_ARCHIVED', 7);
define('SM_QUERY_PUBLIC_DRAFT_CURRENT', 8);

define('SM_QUERY_PUBLIC_LIVE', 9);
define('SM_QUERY_PUBLIC_LIVE_ARCHIVED', 10);
define('SM_QUERY_PUBLIC_LIVE_CURRENT', 11);

define('SM_STATUS_ALL', 0);

define('SM_STATUS_HIDDEN', 1);
define('SM_STATUS_HIDDEN_CHANGED', 2);
define('SM_STATUS_HIDDEN_APPROVED', 3);

define('SM_STATUS_LIVE', 4);
define('SM_STATUS_LIVE_CHANGED', 5);
define('SM_STATUS_LIVE_APPROVED', 6);

define('SM_STATUS_CURRENT', 7);
define('SM_STATUS_ARCHIVED', 8);