<?php

class SmartestHelper{
	
	static function register($helper_name){
	
		// echo 'Registering Helper: '.$helper_name.'<br />';
	
		if(SmartestCache::hasData('smartest_registered_helpers', true)){
			$registered_helpers = SmartestCache::load('smartest_registered_helpers', true);
		}else{
			$registered_helpers = array();
		}
		
		if(!in_array($helper_name, $registered_helpers)){
			$registered_helpers[] = $helper_name;
			sort($registered_helpers);
			SmartestCache::save('smartest_registered_helpers', $registered_helpers, -1, true);
		}
	}
	
	static function getRegisteredHelpers(){
		if(SmartestCache::hasData('smartest_registered_helpers', true)){
			return SmartestCache::load('smartest_registered_helpers', true);
		}else{
			return array();
		}
	}
	
	static function isLoaded($helper_name){
		/* if(SmartestCache::hasData('smartest_registered_helpers', true)){
			$helpers = SmartestCache::load('smartest_registered_helpers', true);
			
			if(in_array($helper_name, $helpers)){
				return true;
			}else{
				return false;
			}
			
		}else{
			return false;
		} */
	}
	
	static function load($helper_name){
		/*if(!self::isLoaded($helper_name)){
			if(file_exists(SM_ROOT_DIR.'System/Helpers/Smartest'.$helper_name.'Helper.class.php')){
				include_once(SM_ROOT_DIR.'System/Helpers/Smartest'.$helper_name.'Helper.class.php');
			}
		} */
	}
	
	static function loadAll(){
		
		// SmartestCache::clear('smartest_available_helpers', true);
		$available_helpers = SmartestCache::load('smartest_available_helpers', true);
		
		// print_r($available_helpers);
		
		$singlefile = '';
		
		// find the helpers if this hasn't already been done
		if(!is_array($available_helpers) || (!is_file(SM_ROOT_DIR.'System/Cache/Includes/helpers.php' && !constant('SM_DEVELOPER_MODE')))){
			
			$helpers = array();
			
			if($res = opendir(SM_ROOT_DIR.'System/Helpers/')){
			
				while (false !== ($file = readdir($res))) {
        		
        			if(preg_match('/Smartest([A-Z]\w+)Helper\.class\.php/', $file, $matches)){
        				// $files[] = $file;
        				// print_r($matches);
        				$helper = array();
        				$helper['name'] = $matches[1];
        				$helper['file'] = $matches[0];
        				$helpers[] = $helper;
        			}
        		
				}
			
				closedir($res);
				
				SmartestCache::save('smartest_available_helpers', $helpers, -1, true);
				$available_helpers = $helpers;
		
			}
		
		
			foreach($available_helpers as $h){
				if(is_file(SM_ROOT_DIR.'System/Helpers/'.$h['file'])){
					if(defined('SM_DEVELOPER_MODE') && constant('SM_DEVELOPER_MODE')){
						include 'System/Helpers/'.$h['file'];
					}else{
						$singlefile .= file_get_contents(SM_ROOT_DIR.'System/Helpers/'.$h['file']);
					}
				}else{
					SmartestCache::clear('smartest_available_helpers', true);
				}
			}
			
			if(!defined('SM_DEVELOPER_MODE') || !constant('SM_DEVELOPER_MODE')){
				$singlefile = str_replace('<?php', "\n\n", $singlefile);
				$singlefile = str_replace('?'.'>', "\n\n", $singlefile);
				$singlefile = "<?php\n\n// Auto-generated by SmartestHelper - Do Not Edit".$singlefile;
			
				file_put_contents(SM_ROOT_DIR.'System/Cache/Includes/helpers.php', $singlefile);
			}
		
		}
		
		if(!defined('SM_DEVELOPER_MODE') || !constant('SM_DEVELOPER_MODE')){
			include SM_ROOT_DIR.'System/Cache/Includes/helpers.php';
		}
	}
}